---
title: "Summary Stats"
author: "Carmen"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
packages <- c("GGally", "skimr")
install.packages(packages)

# load libraries ----
library(GGally)
library(skimr)
library(palmerpenguins)
library(tidyverse)

# Always look at it ----
# View(penguins)

# Check the column names ----
names(penguins) 
```

```{r}
# Check the dimensions ----
dim(penguins) 

# Get a summary ----
summary(penguins)

# Get a summary with {skimr} ----
skim(penguins)
```

```{r}
# Print the first 6 rows ----
head(penguins)

# Print the last 6 rows ----
tail(penguins)
```

```{r}
# Make a pairplot (sort of overwhelming with all data columns) ----
GGally::ggpairs(penguins)
```

```{r}
# Make a pairsplot with a select number of columns and color by species ----
GGally::ggpairs(penguins, 
                columns = 3:6,
                ggplot2::aes(colour = species))
```

```{r}
# Make a histogram of penguin flipper lengths ----
ggplot(data = penguins, aes(x = flipper_length_mm)) + geom_histogram()
```

